=== iwehrman/FireEngine/xml/feConfig.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema" xmlns="">

	<xs:element name="Service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property"  minOccurs="0" maxOccurs="unbounded" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:sequence>
						<xs:element ref="CachedResponseBundle" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:sequence>
						<xs:element ref="SystemConnection" />
						<xs:element ref="Connection" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:sequence>
						<xs:element ref="Template" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:sequence>
						<xs:element ref="DependencySet" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="class" use="required" type="xs:string"/>
			<xs:attribute name="load" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Property">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="value" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="FireEngine">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Service" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="debug" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Connection">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="Constraint" minOccurs="0" />
			</xs:sequence>		
			<xs:attributeGroup ref="connectionAtts" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="SystemConnection">
		<xs:complexType>
			<xs:attributeGroup ref="connectionAtts" />
		</xs:complexType>
	</xs:element>	

	<xs:element name="Constraint">
		<xs:complexType>
			<xs:attribute name="oid" type="xs:integer"/>
			<xs:attribute name="aid" type="xs:integer"/>
			<xs:attribute name="id" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
		
	<xs:attributeGroup name="connectionAtts">
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="user" use="required" type="xs:string"/>
		<xs:attribute name="password" use="required" type="xs:string" />		
		<xs:attribute name="url" use="required" type="xs:anyURI"/>
		<xs:attribute name="driver" use="required" type="xs:string" />
		<xs:attribute name="maxConnections" type="xs:integer"/>
		<xs:attribute name="initConnections" type="xs:integer"/>
		<xs:attribute name="waitIfBusy" type="xs:boolean" />
	</xs:attributeGroup>

	
	<xs:element name="Template">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Block" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>	
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="file" use="required" type="xs:string" />
			<xs:attribute name="cache" type="xs:boolean"/>
			<xs:attribute name="expires" type="xs:integer"/>
			<xs:attribute name="contentType" type="xs:string"/>
			<xs:attribute name="size" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Block">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Dependency" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="file" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>	

	<xs:element name="Parameter">
		<xs:complexType>
			<xs:attribute name="class" use="required" type="xs:string" />
			<xs:attribute name="required" type="xs:boolean" />
			<xs:attribute name="multiple" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="CachedResponseBundle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Dependency" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="uri" use="required" type="xs:anyURI" />
			<xs:attribute name="expires" type="xs:integer"/>
			<xs:attribute name="contentType" type="xs:string"/>
			<xs:attribute name="size" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Dependency">
		<xs:complexType>
			<xs:attribute name="connection" use="required" type="xs:string"/>
			<xs:attribute name="table" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="DependencySet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Dependency" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
			
</xs:schema>

=== iwehrman/FireEngine/etc/FireEngine.xml
<?xml version="1.0" encoding="UTF-8"?>

<FireEngine debug="true"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="http://labfire.com/xml/fe/feConfig.xsd">

 	<Property name="exitoniniterror" value="true" />
 	<Property name="errorPage" value="/error.jsp" />
 	<Property name="loginPage" value="/login.jsp" />
 	<Property name="admin" value="webmaster@labfire.com" />
	<Property name="debug" value="true" />
	<Property name="virtualRoot" value="/@deploy.context@/" />
	<Property name="hostName" value="@deploy.host@:@deploy.port@" />
	<Property name="blank" value="/images/blank.gif" />

	<Service class="com.labfire.fe.auth.AuthenticationService">
  		<Property name="secondstolive" value="1800" />
	</Service>

	<Service class="com.labfire.fe.cache.CacheService">
 	 	<Property name="sleepTime" value="60000" />
	</Service>

	<Service class="com.labfire.fe.db.ConnectionService">
 		<SystemConnection name="fe" user="@db.user@" password="@db.pass@" url="@db.url@" 
			driver="org.postgresql.Driver" maxConnections="50" initConnections="1"
			waitIfBusy="true" />
	</Service>

	<Service class="com.labfire.fe.cron.CronService">
  		<Property name="sleepTime" value="60000" />
	</Service>

	<Service class="com.labfire.fe.log.LogService">
		<Property name="logDir" value="@deploy.approot@/logs" />
		<!-- Property name="format" value="xml" / -->
		<!--Property name="mailto" value="ian@labfire.com" / -->
	</Service>

	<Service class="com.labfire.fe.mail.MailService">
 		<Property name="host" value="mail.labfire.com" />
		<Property name="defaultUser" value="FireEngine" />
		<Property name="defaultPass" value="fe12345" />
	</Service>

	<Service class="com.labfire.fe.auth.OrgAuthenticationService">
  		<Property name="secondstolive" value="1800" />
	</Service>

	<Service class="com.labfire.fe.template.TemplateService">
		<Property name="servletName" value="@deploy.template@" />
		<Property name="default" value="admin" />
		<Property name="parameter" value="page" />
		
		<Template name="admin" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/index.jsp" />
			<Block name="secondary" file="/t_admin/user.jsp" />
		</Template>
		
		<Template name="admin_authentication_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/AuthenticationPanel.jsp">
				<Dependency connection="fe" table="users" />
			</Block>
			<Block name="secondary" file="/t_admin/OrgAuthenticationPanel.jsp">
				<Dependency connection="fe" table="organizations" />
			</Block>
		</Template>
		
		<Template name="admin_authentication_all_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/AuthenticationAllPanel.jsp">
				<Dependency connection="fe" table="users" />
			</Block>
		</Template>
		
		<Template name="admin_authentication_edit_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/AuthenticationEditPanel.jsp">
				<Parameter class="com.labfire.fe.common.TransientUserFactory" />
				<Dependency connection="fe" table="users" />
				<Dependency connection="fe" table="organizations" />
			</Block>
		</Template>	

		<Template name="admin_authentication_insert_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/AuthenticationInsertPanel.jsp" />
		</Template>
		
		<Template name="admin_orgauthentication_all_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/OrgAuthenticationAllPanel.jsp">
				<Dependency connection="fe" table="organizations" />
			</Block>
		</Template>
	
		<Template name="admin_orgauthentication_edit_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/OrgAuthenticationEditPanel.jsp">
				<Parameter class="com.labfire.fe.common.OrganizationFactory" />
				<Dependency connection="fe" table="organizations" />
			</Block>
		</Template>

		<Template name="admin_orgauthentication_insert_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/OrgAuthenticationInsertPanel.jsp" />
		</Template>
		
		<Template name="admin_authorization_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/AuthorizationPanel.jsp">
				<Dependency connection="fe" table="users" />
				<Dependency connection="fe" table="organizations" />
				<Dependency connection="fe" table="requests" />
				<Dependency connection="fe" table="constraints" />
			</Block>
		</Template>
		
		<Template name="admin_authorization_edit_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/AuthorizationEditPanel.jsp">
				<Parameter class="com.labfire.fe.auth.RequestAuthFactory" />
				<Dependency connection="fe" table="users" />
				<Dependency connection="fe" table="organizations" />
				<Dependency connection="fe" table="requests" />
				<Dependency connection="fe" table="constraints" />
			</Block>
		</Template>
		
		<Template name="admin_authorization_insert_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/AuthorizationInsertPanel.jsp">
				<Dependency connection="fe" table="users" />
				<Dependency connection="fe" table="organizations" />
			</Block>
		</Template>
		
		<Template name="admin_constraint_insert_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/ConstraintInsertPanel.jsp">
				<Parameter class="com.labfire.fe.auth.RequestAuthFactory" />
				<Dependency connection="fe" table="users" />
				<Dependency connection="fe" table="organizations" />
				<Dependency connection="fe" table="requests" />
				<Dependency connection="fe" table="constraints" />
			</Block>
		</Template>
		
		<Template name="admin_about" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/about.jsp" />
			<Block name="secondary" file="/t_admin/system.jsp" />
		</Template>
		
		<Template name="admin_status" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/status.jsp" />
		</Template>

		<Template name="admin_log_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/LogPanel.jsp">
				<Dependency connection="fe" table="log" />
			</Block>
		</Template>
		
		<Template name="admin_log_panel_detail" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/LogPanelDetail.jsp">
				<Dependency connection="fe" table="log" />
			</Block>
		</Template>								

		<Template name="admin_cache_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/CachePanel.jsp" />
		</Template>

		<Template name="admin_cron_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/CronPanel.jsp" />
		</Template>	

		<Template name="admin_connection_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/ConnectionPanel.jsp" />
		</Template>
		
		<Template name="admin_prefs_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/PrefsPanel.jsp">
				<Dependency connection="fe" table="prefs" />
			</Block>
		</Template>
		
		<Template name="admin_prefs_insert_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/PrefsInsertPanel.jsp"/>
		</Template>
		
		<Template name="admin_prefs_edit_panel" file="/t_admin/admin_template.jsp">
			<Block name="main" file="/t_admin/PrefsEditPanel.jsp">
				<Dependency connection="fe" table="prefs" />
			</Block>
		</Template>

		<Template name="logout" file="/servlet/com.labfire.fe.auth.LogOutServlet" />
	</Service>
</FireEngine>
